version: '3.8'
services:
  app:
    container_name: app
    image: bitnami/mysql:8.1.0
    networks:
      - learn
    depends_on:
      - db
  db:
    container_name: db
    image: bitnami/mysql:8.1.0
    volumes:
      - mysql_data:/bitnami/mysql/data
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - learn
  nginx:
    container_name: nginx
    image: nginx:alpine3.18-slim
networks:
  learn:
    driver: bridge
volumes:
  mysql_data:
    driver: local